# Generated by Django 5.2.7 on 2026-06-12 03:37

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.JSONField(default=list, verbose_name='對話訊息')),
                ('round_count', models.IntegerField(default=0, verbose_name='目前輪數')),
                ('is_finished', models.BooleanField(default=False, verbose_name='對話結束')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': 'AI 對話',
                'verbose_name_plural': 'AI 對話',
            },
        ),
        migrations.CreateModel(
            name='CognitiveAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vocabulary_richness', models.FloatField(blank=True, null=True, verbose_name='詞彙豐富度')),
                ('sentence_fluency', models.FloatField(blank=True, null=True, verbose_name='語句流暢度')),
                ('topic_coherence', models.FloatField(blank=True, null=True, verbose_name='話題連貫性')),
                ('word_count', models.IntegerField(blank=True, null=True, verbose_name='總字數')),
                ('hesitation_count', models.IntegerField(blank=True, null=True, verbose_name='停頓次數')),
                ('risk_level', models.CharField(choices=[('low', '低風險'), ('medium', '中風險'), ('high', '高風險')], default='low', max_length=10, verbose_name='風險等級')),
                ('summary', models.TextField(blank=True, verbose_name='AI 分析摘要')),
                ('raw_llm_output', models.JSONField(default=dict, verbose_name='LLM 原始輸出')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True, verbose_name='分析時間')),
            ],
            options={
                'verbose_name': '認知分析',
                'verbose_name_plural': '認知分析',
            },
        ),
        migrations.CreateModel(
            name='DiaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(blank=True, help_text='支援 m4a / mp3 / wav，上限 3 分鐘', null=True, upload_to='voiceDiary/media/audio', verbose_name='語音檔案')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='voiceDiary/media/photo', verbose_name='照片')),
                ('transcription', models.TextField(blank=True, verbose_name='Whisper 語音轉文字')),
                ('photo_description', models.TextField(blank=True, verbose_name='照片 AI 描述')),
                ('ai_response', models.TextField(blank=True, verbose_name='AI 溫暖回應')),
                ('status', models.CharField(choices=[('pending', '等待分析'), ('processing', '分析中'), ('done', '完成'), ('failed', '失敗')], default='pending', max_length=20, verbose_name='分析狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '聲影日記',
                'verbose_name_plural': '聲影日記',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('gender', models.CharField(blank=True, max_length=10, verbose_name='性別')),
                ('userbirth', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
