# Generated by Django 5.2.7 on 2026-06-11 12:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=50, null=True, verbose_name='姓名')),
                ('gender', models.CharField(blank=True, max_length=10, null=True, verbose_name='性別')),
                ('userbirth', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('joinday', models.DateField(blank=True, null=True, verbose_name='加入日期')),
            ],
            options={
                'verbose_name': '使用者',
                'verbose_name_plural': '使用者',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='DiaryEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audio_file', models.FileField(blank=True, help_text='支援 m4a / mp3 / wav，上限 3 分鐘', null=True, upload_to='voiceDiary/media/audio', verbose_name='語音檔案')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='voiceDiary/media/photo', verbose_name='照片')),
                ('transcription', models.TextField(blank=True, verbose_name='Whisper 語音轉文字')),
                ('photo_description', models.TextField(blank=True, verbose_name='照片 AI 描述')),
                ('ai_response', models.TextField(blank=True, verbose_name='AI 溫暖回應')),
                ('status', models.CharField(choices=[('pending', '等待分析'), ('processing', '分析中'), ('done', '完成'), ('failed', '失敗')], default='pending', max_length=20, verbose_name='分析狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_entries', to=settings.AUTH_USER_MODEL, verbose_name='用戶')),
            ],
            options={
                'verbose_name': '聲影日記',
                'verbose_name_plural': '聲影日記',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CognitiveAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vocabulary_richness', models.FloatField(blank=True, null=True, verbose_name='詞彙豐富度')),
                ('sentence_fluency', models.FloatField(blank=True, null=True, verbose_name='語句流暢度')),
                ('topic_coherence', models.FloatField(blank=True, null=True, verbose_name='話題連貫性')),
                ('word_count', models.IntegerField(blank=True, null=True, verbose_name='總字數')),
                ('hesitation_count', models.IntegerField(blank=True, null=True, verbose_name='停頓次數')),
                ('risk_level', models.CharField(choices=[('low', '低風險'), ('medium', '中風險'), ('high', '高風險')], default='low', max_length=10, verbose_name='風險等級')),
                ('summary', models.TextField(blank=True, verbose_name='AI 分析摘要')),
                ('raw_llm_output', models.JSONField(default=dict, verbose_name='LLM 原始輸出')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True, verbose_name='分析時間')),
                ('diary_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='Voice.diaryentry', verbose_name='聲影日記')),
            ],
            options={
                'verbose_name': '認知分析',
                'verbose_name_plural': '認知分析',
            },
        ),
        migrations.CreateModel(
            name='AiConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('messages', models.JSONField(default=list, verbose_name='對話訊息')),
                ('round_count', models.IntegerField(default=0, verbose_name='目前輪數')),
                ('is_finished', models.BooleanField(default=False, verbose_name='對話結束')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('diary_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='Voice.diaryentry', verbose_name='聲影日記')),
            ],
            options={
                'verbose_name': 'AI 對話',
                'verbose_name_plural': 'AI 對話',
            },
        ),
    ]
