# Generated by Django 5.2.7 on 2026-06-18 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconversation',
            name='diary',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversation', to='Voice.diaryentry', verbose_name='對應日記'),
        ),
        migrations.AddField(
            model_name='cognitiveanalysis',
            name='diary',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cognitive_analysis', to='Voice.diaryentry', verbose_name='對應日記'),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='diary_text',
            field=models.TextField(blank=True, verbose_name='日記文字'),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='is_shared',
            field=models.BooleanField(default=False, verbose_name='是否分享'),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='share_location',
            field=models.CharField(blank=True, max_length=100, verbose_name='分享位置'),
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='使用者'),
        ),
    ]
