# Generated by Django 5.2.7 on 2026-06-18 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Voice', '0002_aiconversation_diary_cognitiveanalysis_diary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diaryentry',
            name='is_shared',
        ),
        migrations.RemoveField(
            model_name='diaryentry',
            name='share_location',
        ),
    ]
