# Generated by Django 5.2.7 on 2026-06-18 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voice', '0003_remove_diaryentry_is_shared_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cognitiveanalysis',
            options={},
        ),
        migrations.RemoveField(
            model_name='cognitiveanalysis',
            name='hesitation_count',
        ),
        migrations.RemoveField(
            model_name='cognitiveanalysis',
            name='raw_llm_output',
        ),
        migrations.RemoveField(
            model_name='cognitiveanalysis',
            name='sentence_fluency',
        ),
        migrations.RemoveField(
            model_name='cognitiveanalysis',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='cognitiveanalysis',
            name='topic_coherence',
        ),
        migrations.RemoveField(
            model_name='cognitiveanalysis',
            name='vocabulary_richness',
        ),
        migrations.RemoveField(
            model_name='cognitiveanalysis',
            name='word_count',
        ),
        migrations.AddField(
            model_name='cognitiveanalysis',
            name='ai_feedback',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='cognitiveanalysis',
            name='average_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='cognitiveanalysis',
            name='communication_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cognitiveanalysis',
            name='fluency_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cognitiveanalysis',
            name='information_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cognitiveanalysis',
            name='naming_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cognitiveanalysis',
            name='semantic_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cognitiveanalysis',
            name='sentence_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cognitiveanalysis',
            name='suggestion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='cognitiveanalysis',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cognitiveanalysis',
            name='analyzed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cognitiveanalysis',
            name='diary',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cognitive_analysis', to='Voice.diaryentry'),
        ),
        migrations.AlterField(
            model_name='cognitiveanalysis',
            name='risk_level',
            field=models.CharField(choices=[('low', '低風險'), ('medium', '中風險'), ('high', '高風險')], default='low', max_length=10),
        ),
    ]
