# Generated by Django 5.2.7 on 2026-06-18 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voice', '0004_alter_cognitiveanalysis_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiconversation',
            options={'verbose_name': '認知分析結果', 'verbose_name_plural': '認知分析結果'},
        ),
        migrations.AlterField(
            model_name='cognitiveanalysis',
            name='ai_feedback',
            field=models.TextField(blank=True, default='', verbose_name='AI 回饋內容'),
        ),
        migrations.AlterField(
            model_name='cognitiveanalysis',
            name='analyzed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='分析時間'),
        ),
        migrations.AlterField(
            model_name='cognitiveanalysis',
            name='average_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='平均分數'),
        ),
        migrations.AlterField(
            model_name='cognitiveanalysis',
            name='communication_score',
            field=models.IntegerField(default=0, verbose_name='整體溝通能力'),
        ),
        migrations.AlterField(
            model_name='cognitiveanalysis',
            name='diary',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='認知分析結果', to='Voice.diaryentry'),
        ),
        migrations.AlterField(
            model_name='cognitiveanalysis',
            name='fluency_score',
            field=models.IntegerField(default=0, verbose_name='流暢度'),
        ),
        migrations.AlterField(
            model_name='cognitiveanalysis',
            name='information_score',
            field=models.IntegerField(default=0, verbose_name='資訊量'),
        ),
        migrations.AlterField(
            model_name='cognitiveanalysis',
            name='naming_score',
            field=models.IntegerField(default=0, verbose_name='命名能力'),
        ),
        migrations.AlterField(
            model_name='cognitiveanalysis',
            name='risk_level',
            field=models.CharField(choices=[('low', '低風險'), ('medium', '中風險'), ('high', '高風險')], default='low', max_length=10, verbose_name='風險等級'),
        ),
        migrations.AlterField(
            model_name='cognitiveanalysis',
            name='semantic_score',
            field=models.IntegerField(default=0, verbose_name='語意正確性'),
        ),
        migrations.AlterField(
            model_name='cognitiveanalysis',
            name='sentence_score',
            field=models.IntegerField(default=0, verbose_name='句子結構'),
        ),
        migrations.AlterField(
            model_name='cognitiveanalysis',
            name='suggestion',
            field=models.TextField(blank=True, default='', verbose_name='建議內容'),
        ),
    ]
