# Generated by Django 5.2.7 on 2026-06-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voice', '0005_alter_aiconversation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='title',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='日記標題'),
        ),
    ]
