# Generated by Django 5.2.7 on 2026-06-18 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voice', '0006_diaryentry_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiconversation',
            options={'verbose_name': 'AI 追問對話', 'verbose_name_plural': 'AI 追問對話'},
        ),
        migrations.AlterModelOptions(
            name='cognitiveanalysis',
            options={'verbose_name': '認知分析結果', 'verbose_name_plural': '認知分析結果'},
        ),
        migrations.AlterField(
            model_name='cognitiveanalysis',
            name='diary',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cognitive_analysis', to='Voice.diaryentry'),
        ),
        migrations.AlterField(
            model_name='cognitiveanalysis',
            name='total_score',
            field=models.IntegerField(default=0, verbose_name='總分'),
        ),
    ]
