# Generated by Django 5.2.7 on 2026-07-01 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voice', '0007_alter_aiconversation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryentry',
            name='audio_file',
            field=models.FileField(blank=True, help_text='支援 m4a / mp3 / wav，上限 3 分鐘', null=True, upload_to='audio', verbose_name='語音檔案'),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo', verbose_name='照片'),
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(default='菜市場', max_length=50, verbose_name='遊戲名稱')),
                ('score', models.IntegerField(default=0, verbose_name='總分')),
                ('total_questions', models.IntegerField(default=0, verbose_name='總題數')),
                ('accuracy', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='正確率(%)')),
                ('avg_reaction_time', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='平均反應時間(秒)')),
                ('hesitation_count', models.IntegerField(default=0, verbose_name='猶豫次數')),
                ('played_at', models.DateTimeField(auto_now_add=True, verbose_name='遊玩時間')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '遊戲紀錄',
                'verbose_name_plural': '遊戲紀錄',
                'ordering': ['-played_at'],
            },
        ),
    ]
