# Generated by Django 5.2.7 on 2026-06-30 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voice', '0008_add_game_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='voice_replies', verbose_name='語音加油檔案')),
                ('sender_name', models.CharField(blank=True, default='匿名朋友', max_length=30, verbose_name='送出者暱稱')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='送出時間')),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_replies', to='Voice.diaryentry', verbose_name='對應日記')),
            ],
            options={
                'verbose_name': '語音加油',
                'verbose_name_plural': '語音加油',
                'ordering': ['created_at'],
            },
        ),
    ]
