# Generated by Django 5.2.7 on 2026-07-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voice', '0009_add_voice_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicereply',
            name='transcribed_text',
            field=models.TextField(blank=True, default='', verbose_name='語音轉文字'),
        ),
    ]
