# Generated by Django 5.2.7 on 2026-07-03 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voice', '0010_voicereply_transcribed_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diarypost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(blank=True, verbose_name='AI貼文')),
                ('diary_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_posts', to='Voice.diaryentry', verbose_name='對應日記')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
        ),
    ]
