# Generated by Django 5.2.7 on 2026-07-03 09:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voice', '0011_diarypost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diarypost',
            options={'verbose_name': 'AI 貼文', 'verbose_name_plural': 'AI 貼文'},
        ),
        migrations.AddField(
            model_name='diarypost',
            name='category',
            field=models.CharField(blank=True, choices=[('food', '食'), ('clothing', '衣'), ('housing', '住'), ('transport', '行'), ('education', '育'), ('entertainment', '樂')], max_length=20, verbose_name='分類標籤'),
        ),
        migrations.AddField(
            model_name='diarypost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='建立時間'),
            preserve_default=False,
        ),
    ]
