# Generated by Django 5.2.7 on 2026-07-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voice', '0012_alter_diarypost_options_diarypost_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diarypost',
            name='card_image',
            field=models.ImageField(blank=True, null=True, upload_to='share_cards', verbose_name='分享卡片圖片'),
        ),
    ]
