# Generated by Django 5.2.7 on 2026-07-09 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voice', '0013_diarypost_card_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cognitiveanalysis',
            name='invalid_reason',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='無效原因'),
        ),
        migrations.AddField(
            model_name='cognitiveanalysis',
            name='is_valid',
            field=models.BooleanField(default=True, verbose_name='樣本是否有效'),
        ),
        migrations.AlterField(
            model_name='cognitiveanalysis',
            name='average_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='平均分數'),
        ),
        migrations.AlterField(
            model_name='cognitiveanalysis',
            name='communication_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='整體溝通能力'),
        ),
        migrations.AlterField(
            model_name='cognitiveanalysis',
            name='fluency_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='流暢度'),
        ),
        migrations.AlterField(
            model_name='cognitiveanalysis',
            name='information_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='資訊量'),
        ),
        migrations.AlterField(
            model_name='cognitiveanalysis',
            name='naming_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='命名能力'),
        ),
        migrations.AlterField(
            model_name='cognitiveanalysis',
            name='risk_level',
            field=models.CharField(blank=True, choices=[('low', '低風險'), ('medium', '中風險'), ('high', '高風險')], max_length=10, null=True, verbose_name='風險等級'),
        ),
        migrations.AlterField(
            model_name='cognitiveanalysis',
            name='semantic_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='語意正確性'),
        ),
        migrations.AlterField(
            model_name='cognitiveanalysis',
            name='sentence_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='句子結構'),
        ),
        migrations.AlterField(
            model_name='cognitiveanalysis',
            name='total_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='總分'),
        ),
    ]
