# Generated by Django 5.2.7 on 2026-07-09 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voice', '0014_cognitiveanalysis_invalid_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diarypost',
            name='hashtags',
            field=models.JSONField(blank=True, default=list, verbose_name='Hashtag 清單'),
        ),
    ]
