# Generated by Django 5.2.7 on 2026-07-09 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voice', '0015_diarypost_hashtags'),
    ]

    operations = [
        migrations.AddField(
            model_name='diarypost',
            name='suggested_replies',
            field=models.JSONField(blank=True, default=list, verbose_name='建議回覆句'),
        ),
        migrations.CreateModel(
            name='ChatReplyAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_index', models.IntegerField(verbose_name='第幾次回覆')),
                ('audio_file', models.FileField(upload_to='chat_replies/', verbose_name='暫存錄音')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_audios', to='Voice.aiconversation', verbose_name='對應對話')),
            ],
            options={
                'verbose_name': '聊天室暫存錄音',
                'verbose_name_plural': '聊天室暫存錄音',
                'ordering': ['reply_index'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(default='voice_reply', max_length=32, verbose_name='通知類型')),
                ('message', models.CharField(max_length=100, verbose_name='內容')),
                ('is_read', models.BooleanField(default=False, verbose_name='已讀')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('diary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Voice.diaryentry', verbose_name='對應日記')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '站內通知',
                'verbose_name_plural': '站內通知',
                'ordering': ['-created_at'],
            },
        ),
    ]
